### PR TITLE
OpenSCAD ObjectModels

### PR DESCRIPTION
**Pull request by sannfred**
The final variant of table placements at classroom 313 in stl file.

### CODE REVIEW

**Comment by abench** [comment]
I have following suggestions:
- one object per one stl file. All objects should be combined at gazebo world file.
- move all stl files into rodog/rodog_gazebo/models/ directory

**Comment by sannfred** [comment]
Understood, thank you.

**Comment by ldemk** [comment]
Please, rename the pull request in some sensible way

**Comment by abench** [comment]
Delete file tablef.stl from root directory, please.

**Comment by abench** [comment]
All other models are well done and committed into into correct place.

**Comment by ldemk** [comment]
Merged. @sannfred @MrReactive delete the branch after the merge, please. Close all corresponding issues.

**Pull request merged**
