### PR TITLE
Gazebo model of 3rd floor on Tarnavsky

### PR DESCRIPTION
**Pull request by MrReactive**
The third floor is divided into two halves: a college and a faculty where there are 313 audiences and we decided that it is enough to simulate the aisle of the faculty. All dimensions are true.

### CODE REVIEW

**Comment by abench** [comment]
I see only sdf file, not world. Upload world files

**Comment by abench** [comment]
@MrReactive I created world file by myself. See how it look.

**Comment by MrReactive** [comment]
Added world with furniture. I've had some technical problems with my computer but now all is fine. Thank you for test.world.

**Comment by abench** [comment]
@MrReactive . 

Sorry,Your world with furniture looks strange in my computer. 
I made own branch abench_rodog_world_example to help You. 

Run simulations in different worlds using following commands:

roslaunch rodog_gazebo rodog_with_furniture.launch
roslaunch rodog_gazebo rodog.launch
roslaunch rodog_gazebo empty_world.launch

See how directories for models, launches and worlds are organized. 
See what changes were added to package.xml.

Pay attention to tag <scale> </scale> in .sdf and .world files. 
Gazebo by default set it value to <scale>1 1 1</scale> by default, when should be <scale>0.001 0.001 0.001</scale>. And just after save that  value should be corrected manually.

Same with paths to .stl files - they should start from model://<model_name>/ to be computer independent. That moment also should be corrected by hands.

Good manual for world creation for usage in  ROS - http://gazebosim.org/tutorials?tut=ros_roslaunch&cat=connect_ros

Update Your branch according to my example and I will accept this pull request.

**Comment by MrReactive** [comment]
@abench I've created reworked Gazebo world. It seems, I had had a problems (a bug) with my Docker, so I did it on other computer. During the first test it was working properly, but it's still necessary to check it for congruence.

**Comment by abench** [comment]
@MrReactive other_stuff/rodog_world as seen on my computer.
Is it OK?

other_stuff_rodog_world

**Comment by abench** [comment]
I found several bugs in world file.
Now on my computer is looks like below
other_stuff_rodog_world_3

**Pull request merged**
